package com.cloud.study.employee.controller;

import com.cloud.study.domain.BaseController;
import com.cloud.study.domain.Response;
import com.cloud.study.employee.domain.EmployeeDto;
import com.cloud.study.employee.service.EmployeeService;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import javax.ws.rs.Path;

import java.util.concurrent.TimeUnit;

import static java.lang.Thread.sleep;

/**
*  generated by AddClassPlugin plugin
*/

@RestController
public class EmployeeController extends BaseController {

    @Resource
    private EmployeeService employeeService;
    /**
    * 新增
    * @param employeeDto
    * @return
    */
    @PostMapping("employee/add")
    public Response<Boolean> addEmployee(@RequestBody EmployeeDto employeeDto) {
        employeeService.addEmployee(employeeDto);
        return success(Boolean.TRUE);
    }

    /**
     * find by id
     * @param id
     * @return
     */
    @GetMapping("find/employee/{id}")
    public <T> Response<T> findById(@PathVariable("id") Integer id) throws InterruptedException {
        sleep(TimeUnit.SECONDS.toSeconds(1000));
        EmployeeDto employeeDto = employeeService.findById(id);
        return (Response<T>)success(employeeDto);
    }



}