package com.cloud.study.employee.domain;
import com.cloud.study.domain.BaseSearch;
import lombok.Data;
import lombok.EqualsAndHashCode;
/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class EmployeeSearch extends BaseSearch {
}