package com.cloud.study.employee.domain;
import com.cloud.study.employee.entity.Employee;
import lombok.Data;
import lombok.EqualsAndHashCode;
/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class EmployeeDto extends Employee {
}